# TCL File Generated by Component Editor 13.0sp1
# Sun Apr 27 01:09:53 MSD 2025
# DO NOT MODIFY


# 
# MealyMoore_MM_Controller "MealyMoore_MM_Controller" v1.0
#  2025.04.27.01:09:53
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module MealyMoore_MM_Controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME MealyMoore_MM_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME MealyMoore_MM_Controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Mealy_Moore_Controller_LED
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file Mealy_Moore_Controller_LED.vhd VHDL PATH ../MealyMoure_Controller/Mealy_Moore_Controller_LED.vhd TOP_LEVEL_FILE
add_fileset_file memory_map_common.vhd VHDL PATH ../MealyMoure_Controller/memory_map_common.vhd
add_fileset_file Decomp_Mur.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mur/Decomp_Mur.vhd
add_fileset_file ks1_voz_mur.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mur/ks1_voz_mur.vhd
add_fileset_file ks2_out_mur.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mur/ks2_out_mur.vhd
add_fileset_file memory_JKDT.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mur/memory_JKDT.vhd
add_fileset_file Decomp_Mili.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mili/Decomp_Mili.vhd
add_fileset_file ks1_voz_mili.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mili/ks1_voz_mili.vhd
add_fileset_file ks2_out_mili.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mili/ks2_out_mili.vhd
add_fileset_file memory_JKD.vhd VHDL PATH ../MealyMoure_Controller/Decomp_Mili/memory_JKD.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_chipselect chipselect Input 1
add_interface_port s0 avs_s0_byteenable byteenable Input 4
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point LEDR
# 
add_interface LEDR conduit end
set_interface_property LEDR associatedClock clock
set_interface_property LEDR associatedReset reset
set_interface_property LEDR ENABLED true
set_interface_property LEDR EXPORT_OF ""
set_interface_property LEDR PORT_NAME_MAP ""
set_interface_property LEDR SVD_ADDRESS_GROUP ""

add_interface_port LEDR LEDR export Output 18


# 
# connection point LEDG
# 
add_interface LEDG conduit end
set_interface_property LEDG associatedClock clock
set_interface_property LEDG associatedReset reset
set_interface_property LEDG ENABLED true
set_interface_property LEDG EXPORT_OF ""
set_interface_property LEDG PORT_NAME_MAP ""
set_interface_property LEDG SVD_ADDRESS_GROUP ""

add_interface_port LEDG LEDG export Output 9

