# TCL File Generated by Component Editor 13.0sp1
# Sun Apr 27 00:56:11 MSD 2025
# DO NOT MODIFY


# 
# NG_Instr_Controller "NG_Instr_Controller" v1.0
#  2025.04.27.00:56:11
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module NG_Instr_Controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME NG_Instr_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME NG_Instr_Controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CI_NG
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file Johnson_JK_Trig.bdf OTHER PATH ../NG_Controller_Klem/Johnson_JK_Trig.bdf
add_fileset_file NG_custom_instruction_interface.vhd VHDL PATH ../NG_Controller_Klem/NG_custom_instruction_interface.vhd TOP_LEVEL_FILE
add_fileset_file number_generator.bdf OTHER PATH ../NG_Controller_Klem/number_generator.bdf
add_fileset_file KP1533LA2.bdf OTHER PATH ../NG_Controller_Klem/KP1533/KP1533LA2.bdf
add_fileset_file KP1533LA3.bdf OTHER PATH ../NG_Controller_Klem/KP1533/KP1533LA3.bdf
add_fileset_file KP1533LA4.bdf OTHER PATH ../NG_Controller_Klem/KP1533/KP1533LA4.bdf
add_fileset_file KP1533LP16.bdf OTHER PATH ../NG_Controller_Klem/KP1533/KP1533LP16.bdf
add_fileset_file KP1533TB11.bdf OTHER PATH ../NG_Controller_Klem/KP1533/KP1533TB11.bdf


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave_0
# 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2
set_interface_property nios_custom_instruction_slave_0 ENABLED true
set_interface_property nios_custom_instruction_slave_0 EXPORT_OF ""
set_interface_property nios_custom_instruction_slave_0 PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave_0 ncs_clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_result result Output 32
add_interface_port nios_custom_instruction_slave_0 ncs_reset reset Input 1

