# TCL File Generated by Component Editor 13.0sp1
# Sun Apr 27 01:15:51 MSD 2025
# DO NOT MODIFY


# 
# OY_Instr_Controller "OY_Instr_Controller" v1.0
#  2025.04.27.01:15:51
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module OY_Instr_Controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME OY_Instr_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME OY_Instr_Controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL OY_Instruction_Controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file memory_map_common.vhd VHDL PATH ../OY_Instruction_Controller/memory_map_common.vhd
add_fileset_file OY_Instruction_Controller.vhdl VHDL PATH ../OY_Instruction_Controller/OY_Instruction_Controller.vhdl TOP_LEVEL_FILE
add_fileset_file ControlUnit.vhdl VHDL PATH ../OY_Instruction_Controller/OpAut/operation_device/ControlUnit.vhdl
add_fileset_file OperationAutomata.vhdl VHDL PATH ../OY_Instruction_Controller/OpAut/operation_device/OperationAutomata.vhdl


# 
# parameters
# 
add_parameter n INTEGER 16
set_parameter_property n DEFAULT_VALUE 16
set_parameter_property n DISPLAY_NAME n
set_parameter_property n TYPE INTEGER
set_parameter_property n UNITS None
set_parameter_property n ALLOWED_RANGES -2147483648:2147483647
set_parameter_property n HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave_0
# 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2
set_interface_property nios_custom_instruction_slave_0 ENABLED true
set_interface_property nios_custom_instruction_slave_0 EXPORT_OF ""
set_interface_property nios_custom_instruction_slave_0 PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave_0 ncs_clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_reset reset Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_start start Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 ncs_datab datab Input 32
add_interface_port nios_custom_instruction_slave_0 ncs_done done Output 1
add_interface_port nios_custom_instruction_slave_0 ncs_result result Output 32

